-- Unit tests for teacup's pure post-processing functions.
-- Run via: TEACUP_TEST=1 quarto pandoc lua test/unit.lua   (from the repo root)
-- No TeX toolchain required.

dofile("_extensions/teacup/teacup.lua")
local t = _G.teacup_internals
assert(t, "teacup_internals not exposed; is TEACUP_TEST set?")

local failures = 0
local function check(cond, name, detail)
  if cond then
    print("ok   " .. name)
  else
    failures = failures + 1
    print("FAIL " .. name .. (detail and ("\n     " .. detail) or ""))
  end
end

-- A miniature of real dvisvgm output: prolog, sized root, style block with
-- font classes and an embedded font, elements using sentinel colors.
local SAMPLE = [==[<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' width='119.78pt' height='111.46pt' viewBox='-72 -72 119.78 111.46'>
<style type='text/css'>
<![CDATA[text.f0 {font-family:cmr10;font-size:9.96px}
text.f1 {font-family:cmmi10;font-size:9.96px}
@font-face{font-family:cmr10;src:url(data:application/x-font-woff2;base64,AAAA) format('woff2');}]]>
</style>
<g id='page1'>
<clipPath id='pgfcp1'><path d='M0 0H10V10H0Z'/></clipPath>
<linearGradient id='pgfsh1'><stop offset='0' stop-color='#e69f00'/></linearGradient>
<text class='f0' fill='#010101'>V</text>
<path stroke='#e69f00' clip-path='url(#pgfcp1)' d='M0 0L1 1'/>
<path fill='url(#pgfsh1)' d='M0 0L2 2'/>
<use xlink:href='#pgfcp1'/>
</g>
</svg>
]==]
local HASH = "0123456789abcdef0123456789abcdef01234567"
local TAG = HASH:sub(1, 8) -- what unique_tag() yields for the first occurrence

-- default sizing: em width computed from pt width / 10pt base font
local out = t.postprocess(SAMPLE, TAG, nil, "", "")
check(out:find('style="width:11%.9780em;max%-width:100%%;height:auto;overflow:visible;"'),
  "em width = pt/10, overflow backstop present", out:match('style="[^"]*"'))
check(not out:find("width='119"), "width attribute stripped")
check(not out:find("height='111"), "height attribute stripped")
check(out:find("viewBox='%-72 %-72 119%.78 111%.46'"), "viewBox preserved")
check(not out:find("<%?xml"), "xml prolog removed")
check(not out:find("<!%-%-"), "comments removed")

-- width override, including '%' (regression: '%' is special in gsub
-- replacements and once crashed the filter)
out = t.postprocess(SAMPLE, TAG, "30%", "", "")
check(out:find('width:30%%;max%-width', 1, false), "width override with % survives gsub")

-- scoping: hash-derived id, style selectors and font names made per-diagram
out = t.postprocess(SAMPLE, TAG, nil, "", "")
check(out:find('id="teacup%-01234567"'), "hash-derived id on svg root")
check(out:find("#teacup%-01234567 text%.f0"), "text.f0 selector scoped to id")
check(out:find("#teacup%-01234567 text%.f1"), "text.f1 selector scoped to id")
check(out:find("font%-family:cmr10%-01234567"), "font family renamed with hash suffix")
check(not out:find("font%-family:cmr10[^%-]"), "no unscoped font family remains")

-- element ids (clipPaths, gradients, page group) and their url(#)/href
-- references are scoped per diagram; dvisvgm restarts pgfcp1/pgfsh1/page1
-- numbering in every SVG, which collides document-globally when inlined
out = t.postprocess(SAMPLE, TAG, nil, "", "")
check(out:find("id='pgfcp1%-01234567'"), "clipPath id hash-suffixed")
check(out:find("clip%-path='url%(#pgfcp1%-01234567%)'"), "clip-path ref follows its id")
check(out:find("id='pgfsh1%-01234567'"), "gradient id hash-suffixed")
check(out:find("fill='url%(#pgfsh1%-01234567%)'"), "gradient ref follows its id")
check(out:find("id='page1%-01234567'"), "page group id hash-suffixed")
check(out:find("xlink:href='#pgfcp1%-01234567'"), "href ref follows its id")
check(not out:find("url%(#pgfcp1%)"), "no unscoped url reference remains")
check(not out:find("id='pgfcp1'"), "no unscoped element id remains")

-- user-supplied id wins over the hash id
out = t.postprocess(SAMPLE, TAG, nil, "", "fig-kernel")
check(out:find('id="fig%-kernel"'), "user id used on svg root")
check(out:find("#fig%-kernel text%.f0"), "style selectors scoped to user id")

-- extra classes carried onto the root
out = t.postprocess(SAMPLE, TAG, nil, "wide bordered", "")
check(out:find('class="teacup wide bordered"'), "extra classes appended")

-- generated palette CSS: single source of truth checks
local css = t.palette_css()
check(css:find('%[fill="#010101"%]{fill:currentColor}'), "ink maps to currentColor")
check(css:find('%[stroke="#010101"%]{stroke:currentColor}'), "ink stroke maps to currentColor")
check(css:find('%[fill="#e69f00"%]{fill:var%(%-%-teacup%-accent, #e69f00%)}'),
  "accent maps to its variable with sentinel fallback")
check(css:find('var%(%-%-teacup%-canvas, transparent%)'), "canvas falls back to transparent")
local uppercase_hex = false
for hex in css:gmatch('#(%x+)') do
  if hex:find("%u") then uppercase_hex = true end
end
check(not uppercase_hex, "selector hexes are lowercase (dvisvgm emits lowercase hex)")

-- every palette entry appears in both the LaTeX preamble and the CSS
local pre = t.palette_preamble()
for _, c in ipairs(t.PALETTE) do
  check(pre:find("\\definecolor{" .. c.name .. "}{HTML}{" .. c.hex .. "}", 1, true),
    "palette entry '" .. c.name .. "' defined in LaTeX preamble")
  check(css:find('[fill="#' .. c.hex:lower() .. '"]', 1, true),
    "palette entry '" .. c.name .. "' remapped in CSS")
end

-- shared TikZ preamble feeds both the HTML standalone compile and the
-- LaTeX/PDF in-header injection; it must carry the full color setup
local tp = t.tikz_preamble()
check(tp:find("\\usetikzlibrary{", 1, true), "tikz_preamble loads libraries")
check(tp:find("\\definecolor{ink}", 1, true), "tikz_preamble defines ink")
check(tp:find("every picture/.style={color=ink}", 1, true),
  "tikz_preamble sets the every-picture ink default")

-- fix_viewbox replaces dvisvgm's extents (inflated rightward, clipped at the
-- bottom on dvisvgm 3.0.x) with TeX box metrics, keeping min-x/min-y
out = t.fix_viewbox(SAMPLE, 63.5, 100.0, 4.25)
check(out:find("viewBox='%-72 %-72 63%.5000 104%.2500'"),
  "viewBox extents replaced with wd and ht+dp, origin kept",
  out:match("viewBox='[^']*'"))
check(out:find("width='63%.5000pt'"), "width attribute replaced")
check(out:find("height='104%.2500pt'"), "height attribute replaced")
-- and the corrected width drives the em conversion downstream
out = t.postprocess(t.fix_viewbox(SAMPLE, 63.5, 100.0, 4.25), TAG, nil, "", "")
check(out:find('style="width:6%.3500em'), "em width computed from corrected width")
-- an svg without a viewBox is passed through unchanged
check(t.fix_viewbox("<svg width='3pt'></svg>", 1, 1, 1) == "<svg width='3pt'></svg>",
  "svg without viewBox left untouched")

-- meta_to_string must preserve raw TeX, which pandoc.utils.stringify drops.
-- Regression: \usetikzlibrary{arrows} in the preamble metadata was silently
-- discarded because pandoc parses it as a RawInline.
local raw = pandoc.RawInline("tex", "\\usetikzlibrary{arrows}")
check(t.meta_to_string(pandoc.Inlines{raw}) == "\\usetikzlibrary{arrows}",
  "raw TeX inline preserved", t.meta_to_string(pandoc.Inlines{raw}))
check(t.meta_to_string(pandoc.List{
    pandoc.Inlines{pandoc.RawInline("tex", "\\usetikzlibrary{arrows}")},
    pandoc.Inlines{pandoc.RawInline("tex", "\\definecolor{x}{HTML}{FF0000}")},
  }) == "\\usetikzlibrary{arrows}\n\\definecolor{x}{HTML}{FF0000}",
  "YAML list of raw TeX joined with newlines")
check(t.meta_to_string(pandoc.Blocks{
    pandoc.RawBlock("tex", "\\usetikzlibrary{arrows}\n\\usetikzlibrary{shapes}"),
  }) == "\\usetikzlibrary{arrows}\n\\usetikzlibrary{shapes}",
  "block scalar with raw TeX preserved")
check(t.meta_to_string(pandoc.Inlines{
    pandoc.Str("plain"), pandoc.Space(), pandoc.Str("text"),
  }) == "plain text", "plain inline text still stringified")
check(t.meta_to_string(nil) == nil, "nil metadata stays nil")

-- unique_tag disambiguates byte-identical blocks: same hash, distinct tags,
-- so repeated diagrams don't produce duplicate HTML ids (root or defs)
check(t.unique_tag(HASH) == "01234567", "first occurrence: bare hash tag")
check(t.unique_tag(HASH) == "01234567-2", "second occurrence: -2 suffix")
check(t.unique_tag(HASH) == "01234567-3", "third occurrence: -3 suffix")
check(t.unique_tag("fedcba9876543210fedcba9876543210fedcba98") == "fedcba98",
  "different hash starts its own count")
-- a repeat-occurrence tag flows through to root id, fonts, and def ids
out = t.postprocess(SAMPLE, "01234567-2", nil, "", "")
check(out:find('id="teacup%-01234567%-2"'), "repeat root id carries the counter")
check(out:find("font%-family:cmr10%-01234567%-2"), "repeat font suffix carries the counter")
check(out:find("id='pgfcp1%-01234567%-2'"), "repeat def id carries the counter")
check(out:find("clip%-path='url%(#pgfcp1%-01234567%-2%)'"), "repeat def ref carries the counter")

-- log tail helper returns the last lines
local logtext = table.concat({"a", "b", "c", "d", "e"}, "\n")
check(t.tail(logtext, 2):find("d\ne$"), "tail returns last n lines")

print(string.format("\n%d failure(s)", failures))
os.exit(failures == 0 and 0 or 1)
