-- Unit tests for teacup's pure post-processing functions.
-- Run via: TEACUP_TEST=1 quarto pandoc lua test/unit.lua   (from the repo root)
-- No TeX toolchain required.

dofile("_extensions/teacup/teacup.lua")
local t = _G.teacup_internals
assert(t, "teacup_internals not exposed; is TEACUP_TEST set?")

local failures = 0
local function check(cond, name, detail)
  if cond then
    print("ok   " .. name)
  else
    failures = failures + 1
    print("FAIL " .. name .. (detail and ("\n     " .. detail) or ""))
  end
end

-- A miniature of real dvisvgm output: prolog, sized root, style block with
-- font classes and an embedded font, elements using sentinel colors.
local SAMPLE = [==[<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' width='119.78pt' height='111.46pt' viewBox='-72 -72 119.78 111.46'>
<style type='text/css'>
<![CDATA[text.f0 {font-family:cmr10;font-size:9.96px}
text.f1 {font-family:cmmi10;font-size:9.96px}
@font-face{font-family:cmr10;src:url(data:application/x-font-woff2;base64,AAAA) format('woff2');}]]>
</style>
<text class='f0' fill='#010101'>V</text>
<path stroke='#e69f00' d='M0 0L1 1'/>
</svg>
]==]
local HASH = "0123456789abcdef0123456789abcdef01234567"

-- default sizing: em width computed from pt width / 10pt base font
local out = t.postprocess(SAMPLE, HASH, nil, "", "")
check(out:find('style="width:11%.9780em;max%-width:100%%;height:auto;"'),
  "em width = pt/10", out:match('style="[^"]*"'))
check(not out:find("width='119"), "width attribute stripped")
check(not out:find("height='111"), "height attribute stripped")
check(out:find("viewBox='%-72 %-72 119%.78 111%.46'"), "viewBox preserved")
check(not out:find("<%?xml"), "xml prolog removed")
check(not out:find("<!%-%-"), "comments removed")

-- width override, including '%' (regression: '%' is special in gsub
-- replacements and once crashed the filter)
out = t.postprocess(SAMPLE, HASH, "30%", "", "")
check(out:find('width:30%%;max%-width', 1, false), "width override with % survives gsub")

-- scoping: hash-derived id, style selectors and font names made per-diagram
out = t.postprocess(SAMPLE, HASH, nil, "", "")
check(out:find('id="teacup%-01234567"'), "hash-derived id on svg root")
check(out:find("#teacup%-01234567 text%.f0"), "text.f0 selector scoped to id")
check(out:find("#teacup%-01234567 text%.f1"), "text.f1 selector scoped to id")
check(out:find("font%-family:cmr10%-01234567"), "font family renamed with hash suffix")
check(not out:find("font%-family:cmr10[^%-]"), "no unscoped font family remains")

-- user-supplied id wins over the hash id
out = t.postprocess(SAMPLE, HASH, nil, "", "fig-kernel")
check(out:find('id="fig%-kernel"'), "user id used on svg root")
check(out:find("#fig%-kernel text%.f0"), "style selectors scoped to user id")

-- extra classes carried onto the root
out = t.postprocess(SAMPLE, HASH, nil, "wide bordered", "")
check(out:find('class="teacup wide bordered"'), "extra classes appended")

-- generated palette CSS: single source of truth checks
local css = t.palette_css()
check(css:find('%[fill="#010101"%]{fill:currentColor}'), "ink maps to currentColor")
check(css:find('%[stroke="#010101"%]{stroke:currentColor}'), "ink stroke maps to currentColor")
check(css:find('%[fill="#e69f00"%]{fill:var%(%-%-teacup%-accent, #e69f00%)}'),
  "accent maps to its variable with sentinel fallback")
check(css:find('var%(%-%-teacup%-canvas, transparent%)'), "canvas falls back to transparent")
local uppercase_hex = false
for hex in css:gmatch('#(%x+)') do
  if hex:find("%u") then uppercase_hex = true end
end
check(not uppercase_hex, "selector hexes are lowercase (dvisvgm emits lowercase hex)")

-- every palette entry appears in both the LaTeX preamble and the CSS
local pre = t.palette_preamble()
for _, c in ipairs(t.PALETTE) do
  check(pre:find("\\definecolor{" .. c.name .. "}{HTML}{" .. c.hex .. "}", 1, true),
    "palette entry '" .. c.name .. "' defined in LaTeX preamble")
  check(css:find('[fill="#' .. c.hex:lower() .. '"]', 1, true),
    "palette entry '" .. c.name .. "' remapped in CSS")
end

-- shared TikZ preamble feeds both the HTML standalone compile and the
-- LaTeX/PDF in-header injection; it must carry the full color setup
local tp = t.tikz_preamble()
check(tp:find("\\usetikzlibrary{", 1, true), "tikz_preamble loads libraries")
check(tp:find("\\definecolor{ink}", 1, true), "tikz_preamble defines ink")
check(tp:find("every picture/.style={color=ink}", 1, true),
  "tikz_preamble sets the every-picture ink default")

-- log tail helper returns the last lines
local logtext = table.concat({"a", "b", "c", "d", "e"}, "\n")
check(t.tail(logtext, 2):find("d\ne$"), "tail returns last n lines")

print(string.format("\n%d failure(s)", failures))
os.exit(failures == 0 and 0 or 1)
